---
apiVersion: v1
kind: Service
metadata:
  name: demoappservice
spec:
  selector:
    app: demoapp
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inputhandler
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - image: 192.168.39.35:5000/inputhandler
        imagePullPolicy: Always
        name: inputhandler
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inputsender
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
        - image: 192.168.39.35:5000/inputsender
          imagePullPolicy: Always
          name: inputsender
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30