---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inputhandler
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: demoserver
  template:
    metadata:
      labels:
        app: demoserver
    spec:
      containers:
      - image: 192.168.39.35:5000/inputhandler
        imagePullPolicy: Always
        name: inputhandler
        ports:
          - containerPort: 8010
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30